# Generated by Django 3.0.5 on 2020-05-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, null=True)),
                ('foto', models.ImageField(blank=True, default='profile1.png', null=True, upload_to='')),
            ],
        ),
    ]
